troca-games/troca-games/Controllers/JogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using troca_games.Models;

namespace troca_games.Controllers
{
    public class JogosController : Controller
    {
        private readonly AppDbContext _context;

        public JogosController(AppDbContext context)
        {
            _context = context;
        }

        // LISTA DE JOGOS
        [Authorize]
        public async Task<IActionResult> Index(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS DISPONIVEIS
        [Authorize]
        public async Task<IActionResult> Disponiveis(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS A VENDA
        [Authorize]
        public async Task<IActionResult> Comprar(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS PARA ALUGAR
        [Authorize]
        public async Task<IActionResult> Alugar(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS NOVOS
        [Authorize]
        public async Task<IActionResult> Novos(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS USADOS
        [Authorize]
        public async Task<IActionResult> Usados(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // DETALHES JOGO
        [Authorize]
        public async Task<IActionResult> DetalhesJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        // DELETAR JOGO
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeletarJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        [HttpPost, ActionName("DeletarJogo")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeletarJogoConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            _context.Jogos.Remove(jogo);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

troca-games/troca-games/Controllers/JogosReservadosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using troca_games.Models;

namespace troca_games.Controllers
{
    public class JogosReservadosController : Controller
    {
        private readonly AppDbContext _context;

        public JogosReservadosController(AppDbContext context)
        {
            _context = context;
        }

        // LISTA DE JOGOS RESERVADOS
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var jogo = await _context.Jogos
                .OrderBy(x => x.Nome)
                .ToListAsync();

            return View(jogo);
        }

        // RESERVAR JOGO
        [Authorize]
        public async Task<IActionResult> ReservarJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ReservarJogo(int id, Jogo jogo)
        {
            if (id != jogo.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Jogos.Update(jogo);
                await _context.SaveChangesAsync();

                return RedirectToAction("JogoReservado");
            }

            return View();
        }

        // MENSAGEM JOGO RESERVADO
        [AllowAnonymous]
        public IActionResult JogoReservado()
        {
            return View();
        }

        // CANCELAR RESERVA
        [Authorize]
        public async Task<IActionResult> CancelarReserva(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CancelarReserva(int id, Jogo jogo)
        {
            if (id != jogo.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Jogos.Update(jogo);
                await _context.SaveChangesAsync();

                return RedirectToAction("ReservaCancelada");
            }

            return View();
        }

        // MENSAGEM JOGO CANCELADO
        [AllowAnonymous]
        public IActionResult ReservaCancelada()
        {
            return View();
        }

        // DETALHES JOGO
        [Authorize]
        public async Task<IActionResult> DetalhesJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }
    }
}

troca-games/troca-games/Views/JogosReservados/CancelarReserva.cshtml
@model troca_games.Models.Jogo

@{
    ViewData["Title"] = "Cancelar Reserva";

    <style>
        body {
            background-color: rgb(248,248,248);
            font-family: Verdana;
        }
    </style>
}

<h1 style="font-size:30px">Cancelar Reserva</h1>

<h2 style="font-size:18px">Tem certeza que deseja cancelar a Reserva do Jogo?</h2>

<form asp-action="CancelarReserva" style="margin-top:-12px">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <input type="hidden" value="@Model.Nome" id="Nome" name="Nome" required class="form-control" style="font-size:14px" />
    </div>
    <div class="form-group">
        <input type="hidden" value="@Model.Console" id="Console" name="Console" required class="form-control" style="font-size:14px" />
    </div>
    <div class="form-group">
        <input type="hidden" value="@Model.NegociacaoJogo" id="NegociacaoJogo" name="NegociacaoJogo" required class="form-control" style="font-size:14px" />
    </div>
    <div class="form-group">
        <input type="hidden" value="@Model.CondicaoJogo" id="CondicaoJogo" name="CondicaoJogo" required class="form-control" style="font-size:14px" />
    </div>
    <div class="form-group">
        <input type="hidden" value="@Model.Valor" id="Valor" name="Valor" required class="form-control" style="font-size:14px" />
    </div>
    <div class="form-group">
        <input type="hidden" value="@Model.Vendedor" id="Vendedor" name="Vendedor" required class="form-control" style="font-size:14px" />
    </div>
    <div class="form-group">
        <input type="hidden" value="@Model.Email" id="Email" name="Email" required class="form-control" style="font-size:14px" />
    </div>
    <div class="form-group">
        <input type="hidden" value="0" id="Status" name="Status" required class="form-control" style="font-size:14px" />
    </div>
    <div class="form-group">
        <input type="hidden" value="@Model.Comprador" id="Comprador" name="Comprador" required class="form-control" style="font-size:14px" />
    </div>
    <div class="form-group">
        <input type="hidden" value="0" id="Aviso" name="Aviso" required class="form-control" style="font-size:14px" />
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="Cancelar Reserva" class="btn btn-danger" style="font-size:13px" />
        <a asp-action="DetalhesJogo" asp-route-id="@Model.Id" class="btn btn-primary" style="font-size:13px">Voltar</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

troca-games/troca-games/Views/JogosReservados/DetalhesJogo.cshtml
@model troca_games.Models.Jogo

@{
    ViewData["Title"] = "Detalhes Jogo";

    <style>
        body {
            background-color: rgb(248,248,248);
            font-family: Verdana;
        }
    </style>
}

<h1 style="font-size:30px">Detalhes do Jogo</h1>

<div style="width:350px; margin-top:20px">
    <dl class="row">
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Console)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.Console)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.NegociacaoJogo)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.NegociacaoJogo)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.CondicaoJogo)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.CondicaoJogo)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-6" style="font-size:14px">
            R$ @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Vendedor)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.Vendedor)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="CancelarReserva" asp-route-id="@Model.Id" class="btn btn-danger" style="font-size:13px">Cancelar Reserva</a>
    <a asp-action="Index" class="btn btn-primary" style="font-size:13px">Voltar</a>
</div>

troca-games/troca-games/Views/JogosReservados/Index.cshtml
@model IEnumerable<troca_games.Models.Jogo>

@{
    ViewData["Title"] = "Jogos Reservados";

    <style>
        body {
            background-color: rgb(248,248,248);
            font-family: Verdana;
        }
    </style>
}

<h1 style="font-size:30px">Jogos Reservados</h1>

<table class="table" style="margin-top:10px">
    <thead>
        <tr>
            <th>
                <p style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Nome)</p>
            </th>
            <th>
                <p style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Console)</p>
            </th>
            <th>
                <p style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Vendedor)</p>
            </th>
            <th>
                <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Email)</p>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (User.Identity?.Name == item.Comprador & item.Aviso == Aviso.Reservado)
            {
                <tr>
                    <td>
                        <p style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.Nome)</p>
                    </td>
                    <td>
                        <p style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.Console)</p>
                    </td>
                    <td>
                        <p style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.Vendedor)</p>
                    </td>
                    <td>
                        <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.Email)</p>
                    </td>
                    <td>
                        <a asp-action="DetalhesJogo" asp-route-id="@item.Id" class="btn btn-secondary d-none d-lg-block" style="width:90px; font-size:13px">Detalhes</a>
                        <a asp-action="DetalhesJogo" asp-route-id="@item.Id" class="btn btn-secondary d-lg-none"><i class="bi bi-file-earmark-text-fill"></i></a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

troca-games/troca-games/Views/JogosReservados/JogoReservado.cshtml
@model troca_games.Models.Jogo

@{
    ViewData["Title"] = "Jogo Reservado";

    <style>
        body {
            background-color: rgb(248,248,248);
            font-family: Verdana;
        }
    </style>
}

<div class="text-center">
    <h1 style="font-size:30px">Jogo Reservado!</h1>
    <p style="font-size:14px">Entre em contato com o vendedor para a negociação.</p>
    <p style="font-size:14px; color:red">O jogo ficará indisponível por 7 dias.</p>
</div>

troca-games/troca-games/Views/JogosReservados/ReservaCancelada.cshtml
@model troca_games.Models.Jogo

@{
    ViewData["Title"] = "Reserva Cancelada";

    <style>
        body {
            background-color: rgb(248,248,248);
            font-family: Verdana;
        }
    </style>
}

<div class="text-center">
    <h1 style="font-size:30px">Reserva Cancelada!</h1>
</div>

troca-games/troca-games/Views/JogosReservados/ReservarJogo.cshtml
@model troca_games.Models.Jogo

@{
    ViewData["Title"] = "Reservar Jogo";

    <style>
        body {
            background-color: rgb(248,248,248);
            font-family: Verdana;
        }
    </style>
}

<h1 style="font-size:30px">Reservar Jogo</h1>

<h2 style="font-size:18px">Tem certeza que deseja reservar esse jogo?</h2>

<div>
    <dl class="row" style="width:400px; margin-top:20px">
        <dt class="col-5" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-7" style="font-size:14px">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-5" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Console)
        </dt>
        <dd class="col-7" style="font-size:14px">
            @Html.DisplayFor(model => model.Console)
        </dd>
        <dt class="col-5" style="font-size:14px">
            @Html.DisplayNameFor(model => model.NegociacaoJogo)
        </dt>
        <dd class="col-7" style="font-size:14px">
            @Html.DisplayFor(model => model.NegociacaoJogo)
        </dd>
        <dt class="col-5" style="font-size:14px">
            @Html.DisplayNameFor(model => model.CondicaoJogo)
        </dt>
        <dd class="col-7" style="font-size:14px">
            @Html.DisplayFor(model => model.CondicaoJogo)
        </dd>
        <dt class="col-5" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-7" style="font-size:14px">
            R$ @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class="col-5" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Vendedor)
        </dt>
        <dd class="col-7" style="font-size:14px">
            @Html.DisplayFor(model => model.Vendedor)
        </dd>
        <dt class="col-5" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-7" style="font-size:14px">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-5" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-7" style="font-size:14px">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="ReservarJogo">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group" style="margin-bottom:8px">
                <input type="hidden" value="@Model.Nome" id="Nome" name="Nome" required class="form-control" style="font-size:14px" />
            </div>
            <div class="form-group" style="margin-bottom:8px">
                <input type="hidden" value="@Model.Console" id="Console" name="Console" required class="form-control" style="font-size:14px" />
            </div>
            <div class="form-group" style="margin-bottom:8px">
                <input type="hidden" value="@Model.NegociacaoJogo" id="NegociacaoJogo" name="NegociacaoJogo" required class="form-control" style="font-size:14px" />
            </div>
            <div class="form-group" style="margin-bottom:8px">
                <input type="hidden" value="@Model.CondicaoJogo" id="CondicaoJogo" name="CondicaoJogo" required class="form-control" style="font-size:14px" />
            </div>
            <div class="form-group" style="margin-bottom:8px">
                <input type="hidden" value="@Model.Valor" id="Valor" name="Valor" required class="form-control" style="font-size:14px" />
            </div>
            <div class="form-group" style="margin-bottom:8px">
                <input type="hidden" value="@Model.Vendedor" id="Vendedor" name="Vendedor" required class="form-control" style="font-size:14px" />
            </div>
            <div class="form-group" style="margin-bottom:8px">
                <input type="hidden" value="@Model.Email" id="Email" name="Email" required class="form-control" style="font-size:14px" />
            </div>
            <div class="form-group" style="margin-bottom:8px">
                <input type="hidden" value="1" id="Status" name="Status" required class="form-control" style="font-size:14px" />
            </div>
            <div class="form-group" style="margin-bottom:8px">
                <input type="hidden" value="@User.Identity.Name" id="Comprador" name="Comprador" required class="form-control" style="font-size:14px" />
            </div>
            <div class="form-group" style="margin-bottom:8px">
                <input type="hidden" value="1" id="Aviso" name="Aviso" required class="form-control" style="font-size:14px" />
            </div>
            <div class="form-group">
                <input type="submit" value="Reservar Jogo" class="btn btn-success" style="font-size:13px" />
                <a asp-controller="Jogos" asp-action="Index" class="btn btn-danger" style="font-size:13px">Cancelar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}