troca-games/troca-games/Controllers/JogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using troca_games.Models;

namespace troca_games.Controllers
{
    public class JogosController : Controller
    {
        private readonly AppDbContext _context;

        public JogosController(AppDbContext context)
        {
            _context = context;
        }

        // LISTA DE JOGOS
        [Authorize]
        public async Task<IActionResult> Index(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS DISPONIVEIS
        [Authorize]
        public async Task<IActionResult> Disponiveis(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS A VENDA
        [Authorize]
        public async Task<IActionResult> Comprar(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS PARA ALUGAR
        [Authorize]
        public async Task<IActionResult> Alugar(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS NOVOS
        [Authorize]
        public async Task<IActionResult> Novos(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS USADOS
        [Authorize]
        public async Task<IActionResult> Usados(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // DETALHES JOGO
        [Authorize]
        public async Task<IActionResult> DetalhesJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        // DELETAR JOGO
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeletarJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        [HttpPost, ActionName("DeletarJogo")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeletarJogoConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            _context.Jogos.Remove(jogo);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

troca-games/troca-games/Controllers/MeusJogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using troca_games.Models;

namespace troca_games.Controllers
{
    public class MeusJogosController : Controller
    {
        private readonly AppDbContext _context;

        public MeusJogosController(AppDbContext context)
        {
            _context = context;
        }

        // LISTA DE JOGOS DO USUARIO
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var jogo = await _context.Jogos
                .OrderBy(x => x.Nome)
                .ToListAsync();

            return View(jogo);
        }

        // ADICIONAR JOGO
        [Authorize]
        public IActionResult AdicionarJogo()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AdicionarJogo(Jogo jogo)
        {
            if (ModelState.IsValid)
            {
                _context.Jogos.Add(jogo);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(jogo);
        }

        // EDITAR JOGO
        [Authorize]
        public async Task<IActionResult> EditarJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> EditarJogo(int id, Jogo jogo)
        {
            if (id != jogo.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Jogos.Update(jogo);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View();
        }

        // DELETAR JOGO
        [Authorize]
        public async Task<IActionResult> DeletarJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        [HttpPost, ActionName("DeletarJogo")]
        [Authorize]
        public async Task<IActionResult> DeletarJogoConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            _context.Jogos.Remove(jogo);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // DETALHES JOGO
        [Authorize]
        public async Task<IActionResult> DetalhesJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }
    }
}

troca-games/troca-games/Controllers/MinhaContaController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using troca_games.Models;

namespace troca_games.Controllers
{
    public class MinhaContaController : Controller
    {
        private readonly AppDbContext _context;

        public MinhaContaController(AppDbContext context)
        {
            _context = context;
        }

        // CONTA USUARIO
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var usuarios = await _context.Usuarios
                .OrderBy(j => j.Nome)
                .ToListAsync();

            return View(usuarios);
        }

        // EDITAR CONTA
        [Authorize]
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
                return NotFound();

            var usuario = await _context.Usuarios.FindAsync(id);

            if (usuario == null)
                return NotFound();

            return View(usuario);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Editar(int id, Usuario usuario)
        {
            if (id != usuario.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                usuario.Senha = BCrypt.Net.BCrypt.HashPassword(usuario.Senha);

                _context.Usuarios.Update(usuario);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View();
        }

        // DELETAR CONTA
        [Authorize]
        public async Task<IActionResult> Deletar(int? id)
        {
            if (id == null)
                return NotFound();

            var usuario = await _context.Usuarios.FindAsync(id);

            if (usuario == null)
                return NotFound();

            return View(usuario);
        }

        [HttpPost, ActionName("Deletar")]
        [Authorize]
        public async Task<IActionResult> DeletarConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var usuario = await _context.Usuarios.FindAsync(id);

            if (usuario == null)
                return NotFound();

            _context.Usuarios.Remove(usuario);
            await _context.SaveChangesAsync();
            await HttpContext.SignOutAsync();

            return RedirectToAction("ContaDeletada");
        }

        // MENSAGEM CONTA DELETADA
        [AllowAnonymous]
        public IActionResult ContaDeletada()
        {
            return View();
        }
    }
}

troca-games/troca-games/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using troca_games.Models;

namespace troca_games.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly AppDbContext _context;

        public UsuariosController(AppDbContext context)
        {
            _context = context;
        }

        // LISTA DE USUARIOS
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var usuario = await _context.Usuarios
                .OrderBy(x => x.Nome)
                .ToListAsync();

            return View(usuario);
        }

        // CADASTRAR USUARIO
        [AllowAnonymous]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Cadastrar(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.Senha = BCrypt.Net.BCrypt.HashPassword(usuario.Senha);

                _context.Usuarios.Add(usuario);
                await _context.SaveChangesAsync();

                return RedirectToAction("CadastroRealizado");
            }
            return View(usuario);
        }

        // MENSAGEM CADASTRO REALIZADO
        [AllowAnonymous]
        public IActionResult CadastroRealizado()
        {
            return View();
        }

        // LOGIN USUARIO
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(Usuario usuario)
        {
            var dados = await _context.Usuarios
                .Where(u => u.Email == usuario.Email)
                .FirstOrDefaultAsync();

            if (dados == null)
            {
                ViewBag.message = "Usuário ou senha inválidos!";

                return View();
            }

            bool senhaValida = BCrypt.Net.BCrypt.Verify(usuario.Senha, dados.Senha);

            if (senhaValida)
            {
                var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, dados.Nome),
                        new Claim(ClaimTypes.NameIdentifier, dados.Id.ToString()),
                        new Claim(ClaimTypes.Email, dados.Email.ToString()),
                        new Claim(ClaimTypes.Role, dados.Perfil.ToString()),
                    };

                var usuarioIdentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(usuarioIdentity);

                var props = new AuthenticationProperties
                {
                    AllowRefresh = true,
                    ExpiresUtc = DateTime.UtcNow.ToLocalTime().AddHours(8),
                    IsPersistent = true,
                };

                await HttpContext.SignInAsync(principal, props);

                return RedirectToAction("Index", "Jogos");
            }
            else
            {
                ViewBag.message = "Usuário ou senha inválidos!";
            }

            return View();
        }

        // LOGOUT USUARIO
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }

        // DELETAR USUARIO
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeletarUsuario(int? id)
        {
            if (id == null)
                return NotFound();

            var usuario = await _context.Usuarios.FindAsync(id);
            
            if (usuario == null)
                return NotFound();

            return View(usuario);
        }

        [HttpPost, ActionName("DeletarUsuario")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeletarUsuarioConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var usuario = await _context.Usuarios.FindAsync(id);

            if (usuario == null)
                return NotFound();
            
            _context.Usuarios.Remove(usuario);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

troca-games/troca-games/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Troca Games</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/troca_games.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:rgb(248,248,248); font-family:Verdana">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-size:17px">Troca Games</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" style="font-size:14.5px">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Jogos" asp-action="Index">Jogos</a>
                            </li>

                            @if (User.IsInRole("User"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="MeusJogos" asp-action="Index">Meus Jogos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="MeusDesejos" asp-action="Index">Meus Desejos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="JogosReservados" asp-action="Index">Jogos Reservados</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Notificacoes" asp-action="Index">Notificações</a>
                                </li>
                            }
                            
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuários</a>
                                </li>
                            }
                        }

                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MinhaConta" asp-action="Index">Olá, @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Sair</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Cadastrar">Cadastrar</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="position:fixed; bottom:0; width:100%; font-family:Verdana; font-size:13px; background-color:rgb(248,248,248)">
        <div class="container" style="margin-top:10px">
            <p class="text-center">&copy; 2024 - Troca Games</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>