troca-games/troca-games/Models/Jogo.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace troca_games.Models
{
    [Table("Jogos")]
    public class Jogo
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Obrigatório")]
        [Display(Name = "Jogo")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Obrigatório")]
        [Display(Name = "Console")]
        public string Console { get; set; }

        [Display(Name = "Venda/Aluguel")]
        public NegociacaoJogo NegociacaoJogo { get; set; }

        [Display(Name = "Condição")]
        public CondicaoJogo CondicaoJogo { get; set; }

        [Required(ErrorMessage = "Obrigatório")]
        public decimal Valor { get; set; }

        [Display(Name = "Vendedor")]
        public string Vendedor { get; set; }

        [DataType(DataType.EmailAddress)]
        [Display(Name = "E-mail de contato")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Obrigatório")]
        [Display(Name = "Status")]
        public Status Status { get; set; }

        [Display(Name = "Comprador")]
        public string? Comprador { get; set; }

        [Display(Name = "Aviso")]
        public Aviso? Aviso { get; set; }

        public virtual ICollection<Desejo> Desejos { get; set; }
    }

    public enum NegociacaoJogo
    {
        Venda, Aluguel
    }

    public enum CondicaoJogo
    {
        Novo, Usado
    }

    public enum Status
    {
        [Display(Name = "Disponível")]
        Disponivel,
        [Display(Name = "Indisponível")]
        Indisponivel
    }

    public enum Aviso
    {
        Cancelado, Reservado
    }
}

troca-games/troca-games/Controllers/JogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using troca_games.Models;

namespace troca_games.Controllers
{
    public class JogosController : Controller
    {
        private readonly AppDbContext _context;

        public JogosController(AppDbContext context)
        {
            _context = context;
        }

        // LISTA DE JOGOS
        [Authorize]
        public async Task<IActionResult> Index(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS DISPONIVEIS
        [Authorize]
        public async Task<IActionResult> Disponiveis(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS A VENDA
        [Authorize]
        public async Task<IActionResult> Comprar(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS PARA ALUGAR
        [Authorize]
        public async Task<IActionResult> Alugar(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS NOVOS
        [Authorize]
        public async Task<IActionResult> Novos(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // LISTA DE JOGOS USADOS
        [Authorize]
        public async Task<IActionResult> Usados(string searchString)
        {
            var jogo = await _context.Jogos
                .OrderBy(j => j.Nome)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                jogo = jogo.Where(s => s.Nome.Contains(searchString)).ToList();
            }

            return View(jogo);
        }

        // DETALHES JOGO
        [Authorize]
        public async Task<IActionResult> DetalhesJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        // DELETAR JOGO
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeletarJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        [HttpPost, ActionName("DeletarJogo")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeletarJogoConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            _context.Jogos.Remove(jogo);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

troca-games/troca-games/Controllers/JogosReservadosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using troca_games.Models;

namespace troca_games.Controllers
{
    public class JogosReservadosController : Controller
    {
        private readonly AppDbContext _context;

        public JogosReservadosController(AppDbContext context)
        {
            _context = context;
        }

        // LISTA DE JOGOS RESERVADOS
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var jogo = await _context.Jogos
                .OrderBy(x => x.Nome)
                .ToListAsync();

            return View(jogo);
        }

        // RESERVAR JOGO
        [Authorize]
        public async Task<IActionResult> ReservarJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> ReservarJogo(int id, Jogo jogo)
        {
            if (id != jogo.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Jogos.Update(jogo);
                await _context.SaveChangesAsync();

                return RedirectToAction("JogoReservado");
            }

            return View();
        }

        // MENSAGEM JOGO RESERVADO
        [AllowAnonymous]
        public IActionResult JogoReservado()
        {
            return View();
        }

        // CANCELAR RESERVA
        [Authorize]
        public async Task<IActionResult> CancelarReserva(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CancelarReserva(int id, Jogo jogo)
        {
            if (id != jogo.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                _context.Jogos.Update(jogo);
                await _context.SaveChangesAsync();

                return RedirectToAction("ReservaCancelada");
            }

            return View();
        }

        // MENSAGEM JOGO CANCELADO
        [AllowAnonymous]
        public IActionResult ReservaCancelada()
        {
            return View();
        }

        // DETALHES JOGO
        [Authorize]
        public async Task<IActionResult> DetalhesJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }
    }
}

troca-games/troca-games/Controllers/MeusDesejosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using troca_games.Models;

namespace troca_games.Controllers
{
    public class MeusDesejosController : Controller
    {
        private readonly AppDbContext _context;

        public MeusDesejosController(AppDbContext context)
        {
            _context = context;
        }

        // LISTA DE JOGOS DE DESEJOS
        public async Task<IActionResult> Index()
        {
            var desejo = await _context.Desejos
                .Include(d => d.Jogo)
                .ToListAsync();

            return View(desejo);
        }

        // ADICIONAR DESEJO
        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Adicionar(Desejo desejo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(desejo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(desejo);
        }

        // DELETAR DESEJO
        [Authorize]
        public async Task<IActionResult> DeletarDesejo(int? id)
        {
            if (id == null)
                return NotFound();

            var desejo = await _context.Desejos.FindAsync(id);

            if (desejo == null)
                return NotFound();

            return View(desejo);
        }

        [HttpPost, ActionName("DeletarDesejo")]
        [Authorize]
        public async Task<IActionResult> DeletarDesejoConfirmed(int? id)
        {
            if (id == null)
                return NotFound();

            var desejo = await _context.Desejos.FindAsync(id);

            if (desejo == null)
                return NotFound();

            _context.Desejos.Remove(desejo);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // DETALHES JOGO
        [Authorize]
        public async Task<IActionResult> DetalhesJogo(int? id)
        {
            if (id == null)
                return NotFound();

            var jogo = await _context.Jogos.FindAsync(id);

            if (jogo == null)
                return NotFound();

            return View(jogo);
        }
    }
}

troca-games/troca-games/Views/Jogos/Alugar.cshtml
@model IEnumerable<troca_games.Models.Jogo>

@{
    ViewData["Title"] = "Jogos para Alugar";

    <style>
        body {
            background-color: rgb(248,248,248);
            font-family: Verdana;
        }
    </style>
}

<h1 style="font-size:30px">Jogos para Alugar</h1>

<div>
    <a asp-action="Index" class="btn btn-dark" style="font-size:13px">Lista de todos os Jogos</a>
</div>

<div class="row" style="margin-top:10px">
    <div class="col-6">
        <form class="d-flex" asp-controller="Jogos" asp-action="Index">
            <input name="searchString" class="form-control me-1" type="search" placeholder="Pesquisar Jogo" aria-label="Search" style="background-color:whitesmoke; font-size:13px; min-width:250px">
            <a asp-action="Index" class="btn btn-danger" style="font-size:13px">Cancelar</a>
        </form>
    </div>
</div>

<table class="table" style="margin-top:10px">
    <thead>
        <tr>
            <th>
                <p style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Nome)</p>
            </th>
            <th>
                <p style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Console)</p>
            </th>
            <th>
                <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.NegociacaoJogo)</p>
            </th>
            <th>
                <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.CondicaoJogo)</p>
            </th>
            <th>
                <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Valor)</p>
            </th>
            <th>
                <p style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Status)</p>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (item.NegociacaoJogo == NegociacaoJogo.Aluguel)
            {
                <tr>
                    <td>
                        <p style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.Nome)</p>
                    </td>
                    <td>
                        <p style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.Console)</p>
                    </td>
                    <td>
                        <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.NegociacaoJogo)</p>
                    </td>
                    <td>
                        <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.CondicaoJogo)</p>
                    </td>
                    <td>
                        <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">R$ @Html.DisplayFor(modelItem => item.Valor)</p>
                    </td>
                    <td>
                        <p style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.Status)</p>
                    </td>
                    <td>
                        @if (User.IsInRole("User"))
                        {
                            <a asp-action="DetalhesJogo" asp-route-id="@item.Id" class="btn btn-secondary d-none d-lg-block" style="width:90px; font-size:13px">Detalhes</a>
                            <a asp-action="DetalhesJogo" asp-route-id="@item.Id" class="btn btn-secondary d-lg-none" style="padding:4px 8px; font-size:16px"><i class="bi bi-file-earmark-text-fill"></i></a>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-action="DeletarJogo" asp-route-id="@item.Id" class="btn btn-danger" style="font-size:13px">Deletar</a>
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

troca-games/troca-games/Views/Jogos/Aluguel.cshtml
@model IEnumerable<troca_games.Models.Jogo>

@{
    ViewData["Title"] = "Jogos";
}

<h1>Jogos para Alugar</h1>

<div>
    <a asp-action="Index" class="btn btn-outline-dark">Lista de todos os Jogos</a>
</div>
<br />

<div class="row">
    <div class="col-md-6">
        <form class="d-flex" asp-controller="Jogos" asp-action="Index">
            <input name="searchString" class="form-control me-1" type="search" placeholder="Pesquisar Jogo" aria-label="Search">
            <a asp-action="Index" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Console)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NegociacaoJogo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CondicaoJogo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (item.NegociacaoJogo == NegociacaoJogo.Aluguel)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Console)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NegociacaoJogo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CondicaoJogo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        <a asp-action="DetalhesJogo" asp-route-id="@item.Id" class="btn btn-outline-dark">Detalhes</a>
                        @if (item.Status == Status.Disponivel)
                        {
                            <a asp-controller="JogosReservados" asp-action="ReservarJogo" asp-route-id="@item.Id" class="btn btn-outline-success">Reservar</a>
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

troca-games/troca-games/Views/Jogos/Comprar.cshtml
@model IEnumerable<troca_games.Models.Jogo>

@{
    ViewData["Title"] = "Jogos para Comprar";

    <style>
        body {
            background-color: rgb(248,248,248);
            font-family: Verdana;
        }
    </style>
}

<h1 style="font-size:30px">Jogos para Comprar</h1>

<div>
    <a asp-action="Index" class="btn btn-dark" style="font-size:13px">Lista de todos os Jogos</a>
</div>

<div class="row" style="margin-top:10px">
    <div class="col-6">
        <form class="d-flex" asp-controller="Jogos" asp-action="Index">
            <input name="searchString" class="form-control me-1" type="search" placeholder="Pesquisar Jogo" aria-label="Search" style="background-color:whitesmoke; font-size:13px; min-width:250px">
            <a asp-action="Index" class="btn btn-danger" style="font-size:13px">Cancelar</a>
        </form>
    </div>
</div>

<table class="table" style="margin-top:10px">
    <thead>
        <tr>
            <th>
                <p style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Nome)</p>
            </th>
            <th>
                <p style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Console)</p>
            </th>
            <th>
                <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.NegociacaoJogo)</p>
            </th>
            <th>
                <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.CondicaoJogo)</p>
            </th>
            <th>
                <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Valor)</p>
            </th>
            <th>
                <p style="font-size:14px; margin:4px 0">@Html.DisplayNameFor(model => model.Status)</p>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (item.NegociacaoJogo == NegociacaoJogo.Venda)
            {
                <tr>
                    <td>
                        <p style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.Nome)</p>
                    </td>
                    <td>
                        <p style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.Console)</p>
                    </td>
                    <td>
                        <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.NegociacaoJogo)</p>
                    </td>
                    <td>
                        <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.CondicaoJogo)</p>
                    </td>
                    <td>
                        <p class="d-none d-md-block" style="font-size:14px; margin:4px 0">R$ @Html.DisplayFor(modelItem => item.Valor)</p>
                    </td>
                    <td>
                        <p style="font-size:14px; margin:4px 0">@Html.DisplayFor(modelItem => item.Status)</p>
                    </td>
                    <td>
                        @if (User.IsInRole("User"))
                        {
                            <a asp-action="DetalhesJogo" asp-route-id="@item.Id" class="btn btn-secondary d-none d-lg-block" style="width:90px; font-size:13px">Detalhes</a>
                            <a asp-action="DetalhesJogo" asp-route-id="@item.Id" class="btn btn-secondary d-lg-none" style="padding:4px 8px; font-size:16px"><i class="bi bi-file-earmark-text-fill"></i></a>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-action="DeletarJogo" asp-route-id="@item.Id" class="btn btn-danger" style="font-size:13px">Deletar</a>
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

troca-games/troca-games/Views/Jogos/DetalhesJogo.cshtml
@model troca_games.Models.Jogo

@{
    ViewData["Title"] = "Detalhes Jogo";

    <style>
        body {
            background-color: rgb(248,248,248);
            font-family: Verdana;
        }
    </style>
}

<h1 style="font-size:30px">Detalhes do Jogo</h1>

<div style="width:350px; margin-top:20px">
    <dl class="row">
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Console)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.Console)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.NegociacaoJogo)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.NegociacaoJogo)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.CondicaoJogo)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.CondicaoJogo)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-6" style="font-size:14px">
            R$ @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Vendedor)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.Vendedor)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-6" style="font-size:14px">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-6" style="font-size:14px">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <form asp-controller="MeusDesejos" asp-action="Adicionar">
        @if (User.IsInRole("User") & User.Identity.Name != Model.Vendedor & Model.Status == Status.Disponivel)
        {
            <input type="hidden" value="@Model.Id" id="JogoId" name="JogoId" required class="form-control" style="font-size:13px" />
            <input type="hidden" value="@User.Identity.Name" id="Usuario" name="Usuario" required class="form-control" style="font-size:13px" />
            <input type="submit" value="Adicionar à Lista Desejos" class="btn btn-danger" style="font-size:13px" />

            <a asp-controller="JogosReservados" asp-action="ReservarJogo" asp-route-id="@Model.Id" class="btn btn-success" style="font-size:13px">Reservar</a>
        }
        <a asp-action="Index" class="btn btn-primary" style="font-size:13px">Voltar</a>
    </form>
</div>

troca-games/troca-games/Views/Jogos/Venda.cshtml
@model IEnumerable<troca_games.Models.Jogo>

@{
    ViewData["Title"] = "Jogos";
}

<h1>Jogos para Comprar</h1>

<div>
    <a asp-action="Index" class="btn btn-outline-dark">Lista de todos os Jogos</a>
</div>
<br />

<div class="row">
    <div class="col-md-6">
        <form class="d-flex" asp-controller="Jogos" asp-action="Venda">
            <input name="searchString" class="form-control me-1" type="search" placeholder="Pesquisar Jogo" aria-label="Search">
            <a asp-action="Index" class="btn btn-danger">Cancelar</a>
        </form>
    </div>
</div>
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Console)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NegociacaoJogo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CondicaoJogo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (item.NegociacaoJogo == NegociacaoJogo.Venda)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Console)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NegociacaoJogo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CondicaoJogo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        <a asp-action="DetalhesJogo" asp-route-id="@item.Id" class="btn btn-outline-dark">Detalhes</a>
                        @if (item.Status == Status.Disponivel)
                        {
                            <a asp-controller="JogosReservados" asp-action="ReservarJogo" asp-route-id="@item.Id" class="btn btn-outline-success">Reservar</a>
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>